matrix:
  include:
    - language: r
      warnings_are_errors: false
      r:
        - release
        - devel
      cache: packages
      r_packages:
        - covr
      r_build_args: "--no-build-vignettes"
      r_check_args: "--no-build-vignettes"
      after_success:
        - Rscript -e 'library(covr); codecov()'
