matrix:
  include:
    - language: r
      warnings_are_errors: false
      r:
        - release
        - devel
      cache: packages
      r_packages:
        - knitr
        - rmarkdown
        - bookdown
        - prettydoc
